sudo: false
dist: trusty
language: node_js
node_js:
  - "node"
  - "8"
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
install:
  - yarn global add codecov
  - yarn
script:
  - yarn test
after_success:
  - yarn coverage && codecov
cache: yarn
